# configs/unet3d_baseline.yaml
experiment: unet3d_baseline
folds: 5
seed: 42

data:
  root: ./data
  patch_size: [128, 128, 128]
  batch_size: 2
  num_workers: 4

model:
  name: unet3d
  in_channels: 2
  out_channels: 2
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]
  num_res_units: 2

train:
  epochs: 400
  amp: true
  lr: 2.0e-4
  weight_decay: 1.0e-5
  scheduler: cosine         # cosine annealing
  scheduler_T_max: 400      # same as epochs

loss:
  type: dice_ce
  dice_weight: 1.0
  ce_weight: 1.0

logging:
  interval: 50
