# configs/unet2d_multiframe.yaml
experiment: unet2d_multiframe
folds: 5
seed: 42

data:
  root: ./data
  patch_size: [64, 64]   # 2-D model, so (H, W)
  batch_size: 32
  num_workers: 4

model:
  name: unet2d
  in_channels: 64           # 16 magnitude + 16 phase frames
  out_channels: 2
  channels: [8, 16, 32, 64, 128]
  strides:  [2, 2, 2, 2]
  num_res_units: 2

train:
  epochs: 300
  amp: true
  lr: 3.0e-4
  weight_decay: 1.0e-5
  scheduler: cosine
  scheduler_T_max: 400

loss:
  type: dice_ce
  dice_weight: 1.0
  ce_weight: 1.0

logging:
  interval: 20
